version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${BACKEND_PORT}:3333'
    environment:
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
      NODE_ENV: ${BACKEND_NODE_ENV}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${BACKEND_DB_CONNECTION}
      PG_HOST: ${POSTGRES_HOST}
      PG_PORT: ${POSTGRES_PORT}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DB_NAME: ${POSTGRES_DB}
volumes:
  db_data:
